SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS douyin_ai DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE douyin_ai;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(100) DEFAULT '',
  role ENUM('admin','operator') DEFAULT 'operator',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_id VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(255) DEFAULT '',
  user_id INT DEFAULT NULL,
  status ENUM('online','offline','error') DEFAULT 'offline',
  status_message TEXT,
  last_seen DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS personas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_id INT NOT NULL UNIQUE,
  name VARCHAR(100) DEFAULT '????',
  personality JSON,
  style VARCHAR(255) DEFAULT '????',
  tone VARCHAR(255) DEFAULT '????',
  catchphrases JSON,
  forbidden_topics JSON,
  fan_title VARCHAR(100) DEFAULT '???',
  background TEXT,
  strengths JSON,
  greeting_phrase VARCHAR(255) DEFAULT '',
  sign_off VARCHAR(255) DEFAULT '',
  custom_prompt TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_id INT NOT NULL UNIQUE,
  deepseek_api_key VARCHAR(255) DEFAULT '',
  model VARCHAR(50) DEFAULT 'deepseek-chat',
  enabled TINYINT(1) DEFAULT 1,
  reply_length VARCHAR(20) DEFAULT 'medium',
  tone_style VARCHAR(50) DEFAULT 'natural',
  topic_depth VARCHAR(20) DEFAULT 'normal',
  custom_prompt TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS danmaku_log (
  id VARCHAR(100) PRIMARY KEY,
  room_id INT NOT NULL,
  content TEXT NOT NULL,
  username VARCHAR(100) NOT NULL,
  type VARCHAR(20) DEFAULT 'normal',
  filtered TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_replies (
  id VARCHAR(100) PRIMARY KEY,
  room_id INT NOT NULL,
  danmaku_id VARCHAR(100) DEFAULT NULL,
  text TEXT NOT NULL,
  type VARCHAR(20) DEFAULT 'auto',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
